# Generated by Django 3.2.8 on 2021-11-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_tag', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('photo', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('availability', models.CharField(max_length=45)),
                ('building_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySpace.building')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='StudySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_space_id', models.CharField(max_length=16)),
                ('qr_code', models.CharField(max_length=45)),
                ('seats', models.IntegerField()),
                ('table', models.BooleanField()),
                ('availabile', models.BooleanField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySpace.room')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=7)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySpace.student')),
            ],
        ),
    ]
