# Generated by Django 3.2.8 on 2021-11-03 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_tag', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('photo', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('availability', models.CharField(max_length=45)),
                ('building_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySpace.building')),
            ],
        ),
    ]
