# Generated by Django 3.2.8 on 2021-11-03 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_space_id', models.CharField(max_length=16)),
                ('qr_code', models.CharField(max_length=45)),
                ('seats', models.IntegerField()),
                ('table', models.BooleanField()),
                ('availabile', models.BooleanField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySpace.room')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=7)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySpace.student')),
                ('study_space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySpace.studyspace')),
            ],
        ),
    ]
