# Generated by Django 3.2.8 on 2021-11-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='study_space_id',
            field=models.CharField(default='test', max_length=12),
        ),
    ]
