# Generated by Django 3.2.8 on 2021-10-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudySpace', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(max_length=7)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySpace.student')),
                ('study_space_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudySpace.studyspace')),
            ],
        ),
    ]
