declare module 'hls.js'
declare module 'classnames'
declare module 'rc-slider'
declare module 'serpens'
// declare module 'serpens/router'
declare module '*.less'
declare module 'qs'
declare module 'uuid'
// declare module 'mockjs'
declare module 'rc-modal-manager'
declare module 'react-visibility-sensor'
declare module 'co-busboy'
declare module 'rc-tween-one/lib/plugin/ChildrenPlugin'
